r

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -93,27 +93,27 @@ jobs:
           echo "new tag = ${{steps.step1.outputs.new_tag}}"
           echo "tag = ${{steps.step1.outputs.tag}}"
           echo "bumped part = ${{steps.step1.outputs.part}}"
- windows_test:
-    runs-on: windows-latest
-    name: Windows Test Job
-    steps:
-    - name: Step 2
-      run: exit 1  # This step fails
-      #continue-on-error: true    
+#  windows_test:
+#     runs-on: windows-latest
+#     name: Windows Test Job
+#     steps:
+#     - name: Step 2
+#       run: exit 1  # This step fails
+#       #continue-on-error: true    
 
-    - name: Test Failure
-      uses: rjstone/discord-webhook-notify@v1
-      if: failure()
-      with:
-        severity: error
-        details: workflow== Failed!
-        webhookUrl: ${{ secrets.DISCORD__WEBHOOK }}
+#     - name: Test Failure
+#       uses: rjstone/discord-webhook-notify@v1
+#       if: failure()
+#       with:
+#         severity: error
+#         details: workflow== Failed!
+#         webhookUrl: ${{ secrets.DISCORD__WEBHOOK }}
 
-    - name: Windows Test Info
-      uses: rjstone/discord-webhook-notify@v1.0.4
-      if: success()
-      with:
-          severity: info
-          details: Test== Succeeded!
-          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
+#     - name: Windows Test Info
+#       uses: rjstone/discord-webhook-notify@v1.0.4
+#       if: success()
+#       with:
+#           severity: info
+#           details: Test== Succeeded!
+#           webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
 
